In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import zero_one_loss

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data=load_breast_cancer()

In [4]:
X=data.data
y=data.target

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=44, shuffle=True)

In [6]:
LogisticModel=LogisticRegression(penalty="l1",solver='liblinear',C=1.0,max_iter=5000,random_state=33)

In [7]:
LogisticModel.fit(X_train,y_train)

LogisticRegression(max_iter=5000, penalty='l1', random_state=33,
                   solver='liblinear')

In [8]:
LogisticModel.score(X_train,y_train)


0.957286432160804

In [9]:
LogisticModel.score(X_test,y_test)


0.9766081871345029

In [10]:
LogisticModel.classes_


array([0, 1])

In [11]:
LogisticModel.n_iter_

array([92], dtype=int32)

In [12]:
y_pred=LogisticModel.predict(X_test)

In [13]:
y_pred[:10]

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1])

In [14]:
y_train[:10]

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [16]:
acc=accuracy_score(y_test,y_pred)
acc

0.9766081871345029

In [17]:
F1=f1_score(y_test,y_pred,average="micro")
F1

0.9766081871345029

In [18]:
recall=recall_score(y_test,y_pred,average="micro")
recall

0.9766081871345029

In [19]:
pre=precision_recall_fscore_support(y_test,y_pred,average="micro")
pre

(0.9766081871345029, 0.9766081871345029, 0.9766081871345029, None)

In [20]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.98      0.95      0.97        63
           1       0.97      0.99      0.98       108

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171



In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

In [26]:
data =load_breast_cancer()
X=data.data
y=data.target

In [20]:
def function(z):
    return np.log1p(z)

f=FunctionTransformer(func=function)
f.fit(X)
X_f=f.transform(X)


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=44,shuffle=True)


In [28]:
logistic=LogisticRegression(penalty='l1',solver="liblinear",max_iter=100)
logistic.fit(X_train,y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [29]:
result=logistic.predict(X_test)

In [30]:
acc=accuracy_score(y_test,result)
acc

0.9766081871345029

In [31]:
confusion=confusion_matrix(y_test,result)
confusion

array([[ 60,   3],
       [  1, 107]], dtype=int64)

In [34]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

In [35]:
data=load_breast_cancer()
X=data.data
y=data.target

In [36]:
sel=SelectFromModel(RandomForestClassifier(n_estimators=20))
sel.fit(X,y)

SelectFromModel(estimator=RandomForestClassifier(n_estimators=20))

In [37]:
select_features=sel.transform(X)

In [39]:
sfeatures=sel.get_support()
sfeatures

array([ True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True,  True, False, False,  True,
        True, False, False])

In [55]:
X_train,X_test,y_train,y_test=train_test_split(select_features,y,test_size=0.3,random_state=44,shuffle=True)

In [56]:
LogisticModel=LogisticRegression(penalty='l1',solver='liblinear',max_iter=100)
LogisticModel.fit(X_train,y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [57]:
result=LogisticModel.predict(X_test)

In [58]:
acc=accuracy_score(y_test,result)
acc

0.9532163742690059